### user_note index
GET http://localhost:3000/user_notes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTExMjMxMDF9.65Wwwcb4sRNqXL_UVhkv2a-26UzF7AJKQLBPUGsc6z4

### user_note create
POST http://localhost:3000/user_notes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTExMjMxMDF9.65Wwwcb4sRNqXL_UVhkv2a-26UzF7AJKQLBPUGsc6z4
Content-Type: application/json

{
  "student_name": "penny",
  "project_title": "add",
  "note": "penny knows how to add very well"
}



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jeff",
  "email": "jeff@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "drkatie@email.com",
  "password": "password"
}