### user_note index
GET http://localhost:3000/user_notes.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTE2MTgxMjZ9.hwal9AxDl8_FOcQnjTtuchGHiYEI6_HCuAj9QrDJSGw

### user_note create
POST http://localhost:3000/user_notes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTE2MTgxMjZ9.hwal9AxDl8_FOcQnjTtuchGHiYEI6_HCuAj9QrDJSGw
Content-Type: application/json

{
  "student_id": 3,
  "project_id": 3,
  "note": "penny is making progress"
}

### user_note show
GEt http://localhost:3000/user_notes/16.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTE3MzIzNDJ9.IEWUlxE5o97ix3t5gY_5WYyDNmSFb_EjmlYyo8K6r8E



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "zoey",
  "email": "zoey@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "drkatie@email.com",
  "password": "password"
}