### user_note index
GET http://localhost:3000/user_notes

### user_note create
POST http://localhost:3000/user_notes



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jeff",
  "email": "jeff@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jeff@email.com",
  "password": "password"
}